server:
  port: 9001
spring:
  application:
    name: product-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.161.130:3306/springcloud-study
    username: root
    password: admin
  jpa:
    database: Mysql
    show-sql: true
#    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        type: trace
        use_sql_comment: true
eureka:
  instance:
    hostname: 192.168.161.130
    metadata-map: #放置自定义元数据
      user.name: 测试元数据
      user.password: 还是测试元数据
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10 #服务失效时间
    lease-renewal-interval-in-seconds: 5 #服务向注册中心发送心跳的时间间隔
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/ #,http://1127.0.0.1:8000/eureka/
