server:
  port: 9002
  tomcat:
    max-threads: 10
spring:
  zipkin:
    #    base-url: http://127.0.0.1:9411/ #使用rabbit的方式发送消息是不需要配置base-url
    sender:
      #      type: web # 数据传输类型:kafka、rabbit、web
      type: rabbit # 数据传输类型:kafka、rabbit、web
  sleuth:
    sampler:
      probability: 1 #采样比，默认0.1
  rabbitmq:
    host: 192.168.179.129
    username: admin
    password: admin
    port: 5672
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
  application:
    name: order-server
#product-server:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #负载均衡设置为随机策略
#        ConnectionTimeout: 250  #ribbon连接超时时间  毫秒
#        ReadTimeout: 1000 #ribbon读取数据时间  毫秒
#        OkToRetryOnAllOperations: true #是否对所有操作都进行重试
#        MaxAutoRetriesNextServer: 1 #切换实例的重试次数
#        MaxAutoRetries: 1 #对当前实例的重试次数
logging:
  level:
    com.springcloud.study.order.feign: DEBUG #优先级 从高到低分别是 ERROR、WARN、INFO、DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG

